<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="25851" started-at="2018-09-10T09:46:17Z" finished-at="2018-09-10T09:46:43Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="25851" started-at="2018-09-10T09:46:17Z" finished-at="2018-09-10T09:46:43Z">
      <class name="com.automationpractice.testcases.LoginPageTest">
        <test-method status="PASS" signature="setExtent()[pri:0, instance:com.automationpractice.testcases.LoginPageTest@4667ae56]" name="setExtent" is-config="true" duration-ms="169" started-at="2018-09-10T15:16:17Z" finished-at="2018-09-10T15:16:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setExtent -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.automationpractice.testcases.LoginPageTest@4667ae56]" name="setUp" is-config="true" duration-ms="14643" started-at="2018-09-10T15:16:17Z" finished-at="2018-09-10T15:16:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="loginPageLogoTest()[pri:2, instance:com.automationpractice.testcases.LoginPageTest@4667ae56]" name="loginPageLogoTest" duration-ms="81" started-at="2018-09-10T15:16:32Z" finished-at="2018-09-10T15:16:32Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertFalse(Assert.java:63)
	at org.testng.Assert.assertFalse(Assert.java:73)
	at com.automationpractice.testcases.LoginPageTest.loginPageLogoTest(LoginPageTest.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginPageLogoTest -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.automationpractice.testcases.LoginPageTest@4667ae56]" name="tearDown" is-config="true" duration-ms="10623" started-at="2018-09-10T15:16:32Z" finished-at="2018-09-10T15:16:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginPageLogoTest status=FAILURE method=LoginPageTest.loginPageLogoTest()[pri:2, instance:com.automationpractice.testcases.LoginPageTest@4667ae56] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="endReport()[pri:0, instance:com.automationpractice.testcases.LoginPageTest@4667ae56]" name="endReport" is-config="true" duration-ms="332" started-at="2018-09-10T15:16:43Z" finished-at="2018-09-10T15:16:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- com.automationpractice.testcases.LoginPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
